{% set name = "xtensor-python" %}
{% set version = "0.13.0" %}
{% set sha256 = "a72600670c15bdaeab1626ee42b372574654ba64d85109279b9f1165ac514c96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    path: ../.

build:
  number: 0

requirements:
  run:
    - xtensor 
    - pybind11 >=2.3.0

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-python  # [unix]
    - test -f ${PREFIX}/include/xtensor-python/pyarray.hpp  # [unix]
    - if exist %PREFIX%\include\xtensor-python\pyarray.hpp (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python bindings for xtensor, the C++ tensor algebra library'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-python

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
